/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IConfidentialFungibleToken } from "./IConfidentialFungibleToken";
export type { IConfidentialFungibleTokenReceiver } from "./IConfidentialFungibleTokenReceiver";
