/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace BorrowLogicHarness {
  export type ReserveConfigInStruct = {
    borrowCap: BigNumberish;
    supplyCap: BigNumberish;
    collateralFactor: BigNumberish;
    borrowingEnabled: boolean;
    isCollateral: boolean;
    active: boolean;
  };

  export type ReserveConfigInStructOutput = [
    borrowCap: bigint,
    supplyCap: bigint,
    collateralFactor: bigint,
    borrowingEnabled: boolean,
    isCollateral: boolean,
    active: boolean
  ] & {
    borrowCap: bigint;
    supplyCap: bigint;
    collateralFactor: bigint;
    borrowingEnabled: boolean;
    isCollateral: boolean;
    active: boolean;
  };
}

export interface BorrowLogicHarnessInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "executeBorrowTest"
      | "executeRepayTest"
      | "getReserveDataTest"
      | "getUserBorrowBalanceTest"
      | "getUserPositionTest"
      | "setReserveActiveTest"
      | "setReserveBorrowingEnabledTest"
      | "setReserveConfigTest"
      | "setReserveLiquidityTest"
      | "setReservePausedTest"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "executeBorrowTest",
    values: [AddressLike, string, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeRepayTest",
    values: [AddressLike, string, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getReserveDataTest",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserBorrowBalanceTest",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserPositionTest",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setReserveActiveTest",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setReserveBorrowingEnabledTest",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setReserveConfigTest",
    values: [AddressLike, BorrowLogicHarness.ReserveConfigInStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "setReserveLiquidityTest",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setReservePausedTest",
    values: [AddressLike, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "executeBorrowTest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeRepayTest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReserveDataTest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserBorrowBalanceTest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserPositionTest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReserveActiveTest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReserveBorrowingEnabledTest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReserveConfigTest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReserveLiquidityTest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReservePausedTest",
    data: BytesLike
  ): Result;
}

export interface BorrowLogicHarness extends BaseContract {
  connect(runner?: ContractRunner | null): BorrowLogicHarness;
  waitForDeployment(): Promise<this>;

  interface: BorrowLogicHarnessInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  executeBorrowTest: TypedContractMethod<
    [
      asset: AddressLike,
      encryptedHandle: string,
      arg2: BytesLike,
      user: AddressLike
    ],
    [string],
    "nonpayable"
  >;

  executeRepayTest: TypedContractMethod<
    [
      asset: AddressLike,
      encryptedHandle: string,
      arg2: BytesLike,
      arg3: AddressLike
    ],
    [string],
    "nonpayable"
  >;

  getReserveDataTest: TypedContractMethod<
    [asset: AddressLike],
    [
      [
        string,
        string,
        string,
        boolean,
        boolean,
        boolean,
        bigint,
        bigint,
        bigint
      ] & {
        totalSupplied: string;
        totalBorrowed: string;
        availableLiquidity: string;
        active: boolean;
        borrowingEnabled: boolean;
        isCollateral: boolean;
        collateralFactor: bigint;
        supplyCap: bigint;
        borrowCap: bigint;
      }
    ],
    "view"
  >;

  getUserBorrowBalanceTest: TypedContractMethod<
    [user: AddressLike, asset: AddressLike],
    [string],
    "view"
  >;

  getUserPositionTest: TypedContractMethod<
    [user: AddressLike],
    [[boolean, string] & { initialized: boolean; currentDebtAsset: string }],
    "view"
  >;

  setReserveActiveTest: TypedContractMethod<
    [asset: AddressLike, active: boolean],
    [void],
    "nonpayable"
  >;

  setReserveBorrowingEnabledTest: TypedContractMethod<
    [asset: AddressLike, enabled: boolean],
    [void],
    "nonpayable"
  >;

  setReserveConfigTest: TypedContractMethod<
    [asset: AddressLike, config: BorrowLogicHarness.ReserveConfigInStruct],
    [void],
    "nonpayable"
  >;

  setReserveLiquidityTest: TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setReservePausedTest: TypedContractMethod<
    [asset: AddressLike, paused: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "executeBorrowTest"
  ): TypedContractMethod<
    [
      asset: AddressLike,
      encryptedHandle: string,
      arg2: BytesLike,
      user: AddressLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeRepayTest"
  ): TypedContractMethod<
    [
      asset: AddressLike,
      encryptedHandle: string,
      arg2: BytesLike,
      arg3: AddressLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getReserveDataTest"
  ): TypedContractMethod<
    [asset: AddressLike],
    [
      [
        string,
        string,
        string,
        boolean,
        boolean,
        boolean,
        bigint,
        bigint,
        bigint
      ] & {
        totalSupplied: string;
        totalBorrowed: string;
        availableLiquidity: string;
        active: boolean;
        borrowingEnabled: boolean;
        isCollateral: boolean;
        collateralFactor: bigint;
        supplyCap: bigint;
        borrowCap: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserBorrowBalanceTest"
  ): TypedContractMethod<
    [user: AddressLike, asset: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserPositionTest"
  ): TypedContractMethod<
    [user: AddressLike],
    [[boolean, string] & { initialized: boolean; currentDebtAsset: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "setReserveActiveTest"
  ): TypedContractMethod<
    [asset: AddressLike, active: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setReserveBorrowingEnabledTest"
  ): TypedContractMethod<
    [asset: AddressLike, enabled: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setReserveConfigTest"
  ): TypedContractMethod<
    [asset: AddressLike, config: BorrowLogicHarness.ReserveConfigInStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setReserveLiquidityTest"
  ): TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setReservePausedTest"
  ): TypedContractMethod<
    [asset: AddressLike, paused: boolean],
    [void],
    "nonpayable"
  >;

  filters: {};
}
