/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace SupplyLogicHarness {
  export type ReserveConfigInStruct = {
    borrowCap: BigNumberish;
    supplyCap: BigNumberish;
    collateralFactor: BigNumberish;
    borrowingEnabled: boolean;
    isCollateral: boolean;
    active: boolean;
  };

  export type ReserveConfigInStructOutput = [
    borrowCap: bigint,
    supplyCap: bigint,
    collateralFactor: bigint,
    borrowingEnabled: boolean,
    isCollateral: boolean,
    active: boolean
  ] & {
    borrowCap: bigint;
    supplyCap: bigint;
    collateralFactor: bigint;
    borrowingEnabled: boolean;
    isCollateral: boolean;
    active: boolean;
  };
}

export interface SupplyLogicHarnessInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "executeSupplyTest"
      | "executeWithdrawTest"
      | "getReserveDataTest"
      | "getUserBalanceTest"
      | "getUserPositionTest"
      | "setReserveActiveTest"
      | "setReserveConfigTest"
      | "setReserveLiquidityTest"
      | "setReservePausedTest"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "SupplyExecuted" | "WithdrawExecuted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "executeSupplyTest",
    values: [AddressLike, string, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeWithdrawTest",
    values: [AddressLike, string, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getReserveDataTest",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserBalanceTest",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserPositionTest",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setReserveActiveTest",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setReserveConfigTest",
    values: [AddressLike, SupplyLogicHarness.ReserveConfigInStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "setReserveLiquidityTest",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setReservePausedTest",
    values: [AddressLike, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "executeSupplyTest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeWithdrawTest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReserveDataTest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserBalanceTest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserPositionTest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReserveActiveTest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReserveConfigTest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReserveLiquidityTest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReservePausedTest",
    data: BytesLike
  ): Result;
}

export namespace SupplyExecutedEvent {
  export type InputTuple = [
    user: AddressLike,
    asset: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [user: string, asset: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    asset: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawExecutedEvent {
  export type InputTuple = [
    user: AddressLike,
    asset: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [user: string, asset: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    asset: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SupplyLogicHarness extends BaseContract {
  connect(runner?: ContractRunner | null): SupplyLogicHarness;
  waitForDeployment(): Promise<this>;

  interface: SupplyLogicHarnessInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  executeSupplyTest: TypedContractMethod<
    [
      asset: AddressLike,
      encryptedHandle: string,
      arg2: BytesLike,
      arg3: AddressLike
    ],
    [string],
    "nonpayable"
  >;

  executeWithdrawTest: TypedContractMethod<
    [
      asset: AddressLike,
      encryptedHandle: string,
      arg2: BytesLike,
      user: AddressLike
    ],
    [string],
    "nonpayable"
  >;

  getReserveDataTest: TypedContractMethod<
    [asset: AddressLike],
    [
      [
        string,
        string,
        string,
        boolean,
        boolean,
        boolean,
        bigint,
        bigint,
        bigint
      ] & {
        totalSupplied: string;
        totalBorrowed: string;
        availableLiquidity: string;
        active: boolean;
        borrowingEnabled: boolean;
        isCollateral: boolean;
        collateralFactor: bigint;
        supplyCap: bigint;
        borrowCap: bigint;
      }
    ],
    "view"
  >;

  getUserBalanceTest: TypedContractMethod<
    [user: AddressLike, asset: AddressLike],
    [string],
    "view"
  >;

  getUserPositionTest: TypedContractMethod<
    [user: AddressLike],
    [[boolean, string] & { initialized: boolean; currentDebtAsset: string }],
    "view"
  >;

  setReserveActiveTest: TypedContractMethod<
    [asset: AddressLike, active: boolean],
    [void],
    "nonpayable"
  >;

  setReserveConfigTest: TypedContractMethod<
    [asset: AddressLike, config: SupplyLogicHarness.ReserveConfigInStruct],
    [void],
    "nonpayable"
  >;

  setReserveLiquidityTest: TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setReservePausedTest: TypedContractMethod<
    [asset: AddressLike, paused: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "executeSupplyTest"
  ): TypedContractMethod<
    [
      asset: AddressLike,
      encryptedHandle: string,
      arg2: BytesLike,
      arg3: AddressLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeWithdrawTest"
  ): TypedContractMethod<
    [
      asset: AddressLike,
      encryptedHandle: string,
      arg2: BytesLike,
      user: AddressLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getReserveDataTest"
  ): TypedContractMethod<
    [asset: AddressLike],
    [
      [
        string,
        string,
        string,
        boolean,
        boolean,
        boolean,
        bigint,
        bigint,
        bigint
      ] & {
        totalSupplied: string;
        totalBorrowed: string;
        availableLiquidity: string;
        active: boolean;
        borrowingEnabled: boolean;
        isCollateral: boolean;
        collateralFactor: bigint;
        supplyCap: bigint;
        borrowCap: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserBalanceTest"
  ): TypedContractMethod<
    [user: AddressLike, asset: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserPositionTest"
  ): TypedContractMethod<
    [user: AddressLike],
    [[boolean, string] & { initialized: boolean; currentDebtAsset: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "setReserveActiveTest"
  ): TypedContractMethod<
    [asset: AddressLike, active: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setReserveConfigTest"
  ): TypedContractMethod<
    [asset: AddressLike, config: SupplyLogicHarness.ReserveConfigInStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setReserveLiquidityTest"
  ): TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setReservePausedTest"
  ): TypedContractMethod<
    [asset: AddressLike, paused: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "SupplyExecuted"
  ): TypedContractEvent<
    SupplyExecutedEvent.InputTuple,
    SupplyExecutedEvent.OutputTuple,
    SupplyExecutedEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawExecuted"
  ): TypedContractEvent<
    WithdrawExecutedEvent.InputTuple,
    WithdrawExecutedEvent.OutputTuple,
    WithdrawExecutedEvent.OutputObject
  >;

  filters: {
    "SupplyExecuted(address,address,uint64)": TypedContractEvent<
      SupplyExecutedEvent.InputTuple,
      SupplyExecutedEvent.OutputTuple,
      SupplyExecutedEvent.OutputObject
    >;
    SupplyExecuted: TypedContractEvent<
      SupplyExecutedEvent.InputTuple,
      SupplyExecutedEvent.OutputTuple,
      SupplyExecutedEvent.OutputObject
    >;

    "WithdrawExecuted(address,address,uint64)": TypedContractEvent<
      WithdrawExecutedEvent.InputTuple,
      WithdrawExecutedEvent.OutputTuple,
      WithdrawExecutedEvent.OutputObject
    >;
    WithdrawExecuted: TypedContractEvent<
      WithdrawExecutedEvent.InputTuple,
      WithdrawExecutedEvent.OutputTuple,
      WithdrawExecutedEvent.OutputObject
    >;
  };
}
