/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ConfidentialTokenSwapperInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addTokenPair"
      | "emergencyWithdraw"
      | "finalizeSwap"
      | "getConfidentialToken"
      | "getERC20Token"
      | "getPendingSwap"
      | "isTokenSupported"
      | "owner"
      | "protocolId"
      | "removeTokenPair"
      | "renounceOwnership"
      | "swapConfidentialToERC20"
      | "swapERC20ToConfidential"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ConfidentialToERC20SwapFinalized"
      | "ConfidentialToERC20SwapInitiated"
      | "DecryptionFulfilled"
      | "ERC20ToConfidentialSwap"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addTokenPair",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeSwap",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getConfidentialToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getERC20Token",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingSwap",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isTokenSupported",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeTokenPair",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "swapConfidentialToERC20",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "swapERC20ToConfidential",
    values: [AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addTokenPair",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeSwap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getConfidentialToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getERC20Token",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingSwap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTokenSupported",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeTokenPair",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapConfidentialToERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapERC20ToConfidential",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace ConfidentialToERC20SwapFinalizedEvent {
  export type InputTuple = [
    user: AddressLike,
    requestId: BigNumberish,
    amount: BigNumberish,
    erc20: AddressLike
  ];
  export type OutputTuple = [
    user: string,
    requestId: bigint,
    amount: bigint,
    erc20: string
  ];
  export interface OutputObject {
    user: string;
    requestId: bigint;
    amount: bigint;
    erc20: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConfidentialToERC20SwapInitiatedEvent {
  export type InputTuple = [
    user: AddressLike,
    confidential: AddressLike,
    requestId: BigNumberish,
    erc20: AddressLike
  ];
  export type OutputTuple = [
    user: string,
    confidential: string,
    requestId: bigint,
    erc20: string
  ];
  export interface OutputObject {
    user: string;
    confidential: string;
    requestId: bigint;
    erc20: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DecryptionFulfilledEvent {
  export type InputTuple = [requestID: BigNumberish];
  export type OutputTuple = [requestID: bigint];
  export interface OutputObject {
    requestID: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ERC20ToConfidentialSwapEvent {
  export type InputTuple = [
    user: AddressLike,
    erc20: AddressLike,
    amount: BigNumberish,
    confidential: AddressLike
  ];
  export type OutputTuple = [
    user: string,
    erc20: string,
    amount: bigint,
    confidential: string
  ];
  export interface OutputObject {
    user: string;
    erc20: string;
    amount: bigint;
    confidential: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ConfidentialTokenSwapper extends BaseContract {
  connect(runner?: ContractRunner | null): ConfidentialTokenSwapper;
  waitForDeployment(): Promise<this>;

  interface: ConfidentialTokenSwapperInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addTokenPair: TypedContractMethod<
    [erc20Token: AddressLike, confidentialToken: AddressLike],
    [void],
    "nonpayable"
  >;

  emergencyWithdraw: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  finalizeSwap: TypedContractMethod<
    [
      requestId: BigNumberish,
      cleartexts: BytesLike,
      decryptionProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getConfidentialToken: TypedContractMethod<
    [erc20Token: AddressLike],
    [string],
    "view"
  >;

  getERC20Token: TypedContractMethod<
    [confToken: AddressLike],
    [string],
    "view"
  >;

  getPendingSwap: TypedContractMethod<
    [requestId: BigNumberish],
    [[string, string] & { receiver: string; erc20Token: string }],
    "view"
  >;

  isTokenSupported: TypedContractMethod<
    [erc20Token: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  removeTokenPair: TypedContractMethod<
    [erc20Token: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  swapConfidentialToERC20: TypedContractMethod<
    [confToken: AddressLike, encryptedAmount: BytesLike, inputProof: BytesLike],
    [bigint],
    "nonpayable"
  >;

  swapERC20ToConfidential: TypedContractMethod<
    [erc20Token: AddressLike, amount: BigNumberish, to: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addTokenPair"
  ): TypedContractMethod<
    [erc20Token: AddressLike, confidentialToken: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "finalizeSwap"
  ): TypedContractMethod<
    [
      requestId: BigNumberish,
      cleartexts: BytesLike,
      decryptionProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getConfidentialToken"
  ): TypedContractMethod<[erc20Token: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getERC20Token"
  ): TypedContractMethod<[confToken: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getPendingSwap"
  ): TypedContractMethod<
    [requestId: BigNumberish],
    [[string, string] & { receiver: string; erc20Token: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "isTokenSupported"
  ): TypedContractMethod<[erc20Token: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "removeTokenPair"
  ): TypedContractMethod<[erc20Token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "swapConfidentialToERC20"
  ): TypedContractMethod<
    [confToken: AddressLike, encryptedAmount: BytesLike, inputProof: BytesLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapERC20ToConfidential"
  ): TypedContractMethod<
    [erc20Token: AddressLike, amount: BigNumberish, to: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ConfidentialToERC20SwapFinalized"
  ): TypedContractEvent<
    ConfidentialToERC20SwapFinalizedEvent.InputTuple,
    ConfidentialToERC20SwapFinalizedEvent.OutputTuple,
    ConfidentialToERC20SwapFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "ConfidentialToERC20SwapInitiated"
  ): TypedContractEvent<
    ConfidentialToERC20SwapInitiatedEvent.InputTuple,
    ConfidentialToERC20SwapInitiatedEvent.OutputTuple,
    ConfidentialToERC20SwapInitiatedEvent.OutputObject
  >;
  getEvent(
    key: "DecryptionFulfilled"
  ): TypedContractEvent<
    DecryptionFulfilledEvent.InputTuple,
    DecryptionFulfilledEvent.OutputTuple,
    DecryptionFulfilledEvent.OutputObject
  >;
  getEvent(
    key: "ERC20ToConfidentialSwap"
  ): TypedContractEvent<
    ERC20ToConfidentialSwapEvent.InputTuple,
    ERC20ToConfidentialSwapEvent.OutputTuple,
    ERC20ToConfidentialSwapEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "ConfidentialToERC20SwapFinalized(address,uint256,uint64,address)": TypedContractEvent<
      ConfidentialToERC20SwapFinalizedEvent.InputTuple,
      ConfidentialToERC20SwapFinalizedEvent.OutputTuple,
      ConfidentialToERC20SwapFinalizedEvent.OutputObject
    >;
    ConfidentialToERC20SwapFinalized: TypedContractEvent<
      ConfidentialToERC20SwapFinalizedEvent.InputTuple,
      ConfidentialToERC20SwapFinalizedEvent.OutputTuple,
      ConfidentialToERC20SwapFinalizedEvent.OutputObject
    >;

    "ConfidentialToERC20SwapInitiated(address,address,uint256,address)": TypedContractEvent<
      ConfidentialToERC20SwapInitiatedEvent.InputTuple,
      ConfidentialToERC20SwapInitiatedEvent.OutputTuple,
      ConfidentialToERC20SwapInitiatedEvent.OutputObject
    >;
    ConfidentialToERC20SwapInitiated: TypedContractEvent<
      ConfidentialToERC20SwapInitiatedEvent.InputTuple,
      ConfidentialToERC20SwapInitiatedEvent.OutputTuple,
      ConfidentialToERC20SwapInitiatedEvent.OutputObject
    >;

    "DecryptionFulfilled(uint256)": TypedContractEvent<
      DecryptionFulfilledEvent.InputTuple,
      DecryptionFulfilledEvent.OutputTuple,
      DecryptionFulfilledEvent.OutputObject
    >;
    DecryptionFulfilled: TypedContractEvent<
      DecryptionFulfilledEvent.InputTuple,
      DecryptionFulfilledEvent.OutputTuple,
      DecryptionFulfilledEvent.OutputObject
    >;

    "ERC20ToConfidentialSwap(address,address,uint256,address)": TypedContractEvent<
      ERC20ToConfidentialSwapEvent.InputTuple,
      ERC20ToConfidentialSwapEvent.OutputTuple,
      ERC20ToConfidentialSwapEvent.OutputObject
    >;
    ERC20ToConfidentialSwap: TypedContractEvent<
      ERC20ToConfidentialSwapEvent.InputTuple,
      ERC20ToConfidentialSwapEvent.OutputTuple,
      ERC20ToConfidentialSwapEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
