/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ConfidentialLendingVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "asset"
      | "getAuthorizedUserCount"
      | "getEncryptedShares"
      | "getEncryptedTotalAssets"
      | "getEncryptedTotalShares"
      | "isUserAuthorized"
      | "onConfidentialTransferReceived"
      | "owner"
      | "protocolId"
      | "renounceOwnership"
      | "supply"
      | "transferOwnership"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ConfidentialSupply"
      | "ConfidentialWithdraw"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(functionFragment: "asset", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getAuthorizedUserCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedShares",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedTotalAssets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedTotalShares",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isUserAuthorized",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onConfidentialTransferReceived",
    values: [AddressLike, AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "supply",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "asset", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAuthorizedUserCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedTotalAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedTotalShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isUserAuthorized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onConfidentialTransferReceived",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "supply", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace ConfidentialSupplyEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConfidentialWithdrawEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ConfidentialLendingVault extends BaseContract {
  connect(runner?: ContractRunner | null): ConfidentialLendingVault;
  waitForDeployment(): Promise<this>;

  interface: ConfidentialLendingVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  asset: TypedContractMethod<[], [string], "view">;

  getAuthorizedUserCount: TypedContractMethod<[], [bigint], "view">;

  getEncryptedShares: TypedContractMethod<
    [user: AddressLike],
    [string],
    "view"
  >;

  getEncryptedTotalAssets: TypedContractMethod<[], [string], "view">;

  getEncryptedTotalShares: TypedContractMethod<[], [string], "view">;

  isUserAuthorized: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  onConfidentialTransferReceived: TypedContractMethod<
    [arg0: AddressLike, from: AddressLike, amount: BytesLike, arg3: BytesLike],
    [string],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  supply: TypedContractMethod<
    [encryptedAmount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<
    [encryptedAmount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "asset"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAuthorizedUserCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEncryptedShares"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getEncryptedTotalAssets"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getEncryptedTotalShares"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isUserAuthorized"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "onConfidentialTransferReceived"
  ): TypedContractMethod<
    [arg0: AddressLike, from: AddressLike, amount: BytesLike, arg3: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supply"
  ): TypedContractMethod<
    [encryptedAmount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [encryptedAmount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ConfidentialSupply"
  ): TypedContractEvent<
    ConfidentialSupplyEvent.InputTuple,
    ConfidentialSupplyEvent.OutputTuple,
    ConfidentialSupplyEvent.OutputObject
  >;
  getEvent(
    key: "ConfidentialWithdraw"
  ): TypedContractEvent<
    ConfidentialWithdrawEvent.InputTuple,
    ConfidentialWithdrawEvent.OutputTuple,
    ConfidentialWithdrawEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "ConfidentialSupply(address)": TypedContractEvent<
      ConfidentialSupplyEvent.InputTuple,
      ConfidentialSupplyEvent.OutputTuple,
      ConfidentialSupplyEvent.OutputObject
    >;
    ConfidentialSupply: TypedContractEvent<
      ConfidentialSupplyEvent.InputTuple,
      ConfidentialSupplyEvent.OutputTuple,
      ConfidentialSupplyEvent.OutputObject
    >;

    "ConfidentialWithdraw(address)": TypedContractEvent<
      ConfidentialWithdrawEvent.InputTuple,
      ConfidentialWithdrawEvent.OutputTuple,
      ConfidentialWithdrawEvent.OutputObject
    >;
    ConfidentialWithdraw: TypedContractEvent<
      ConfidentialWithdrawEvent.InputTuple,
      ConfidentialWithdrawEvent.OutputTuple,
      ConfidentialWithdrawEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
