/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ConfidentialTokenSwapperSimpleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "emergencyWithdraw"
      | "finalizeSwap"
      | "getAddresses"
      | "owner"
      | "protocolId"
      | "renounceOwnership"
      | "swapConfidentialToERC20"
      | "swapERC20ToConfidential"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ConfidentialToERC20Swap"
      | "ERC20ToConfidentialSwap"
      | "OwnershipTransferred"
      | "SwapFinalized"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeSwap",
    values: [BigNumberish, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getAddresses",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "swapConfidentialToERC20",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "swapERC20ToConfidential",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeSwap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapConfidentialToERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapERC20ToConfidential",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace ConfidentialToERC20SwapEvent {
  export type InputTuple = [user: AddressLike, requestId: BigNumberish];
  export type OutputTuple = [user: string, requestId: bigint];
  export interface OutputObject {
    user: string;
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ERC20ToConfidentialSwapEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapFinalizedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    user: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [requestId: bigint, user: string, amount: bigint];
  export interface OutputObject {
    requestId: bigint;
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ConfidentialTokenSwapperSimple extends BaseContract {
  connect(runner?: ContractRunner | null): ConfidentialTokenSwapperSimple;
  waitForDeployment(): Promise<this>;

  interface: ConfidentialTokenSwapperSimpleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  emergencyWithdraw: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  finalizeSwap: TypedContractMethod<
    [requestId: BigNumberish, decryptedAmounts: BytesLike[]],
    [void],
    "nonpayable"
  >;

  getAddresses: TypedContractMethod<
    [],
    [[string, string] & { cWETH: string; weth: string }],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  swapConfidentialToERC20: TypedContractMethod<
    [encryptedInput: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  swapERC20ToConfidential: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "finalizeSwap"
  ): TypedContractMethod<
    [requestId: BigNumberish, decryptedAmounts: BytesLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAddresses"
  ): TypedContractMethod<
    [],
    [[string, string] & { cWETH: string; weth: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "swapConfidentialToERC20"
  ): TypedContractMethod<
    [encryptedInput: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapERC20ToConfidential"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ConfidentialToERC20Swap"
  ): TypedContractEvent<
    ConfidentialToERC20SwapEvent.InputTuple,
    ConfidentialToERC20SwapEvent.OutputTuple,
    ConfidentialToERC20SwapEvent.OutputObject
  >;
  getEvent(
    key: "ERC20ToConfidentialSwap"
  ): TypedContractEvent<
    ERC20ToConfidentialSwapEvent.InputTuple,
    ERC20ToConfidentialSwapEvent.OutputTuple,
    ERC20ToConfidentialSwapEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SwapFinalized"
  ): TypedContractEvent<
    SwapFinalizedEvent.InputTuple,
    SwapFinalizedEvent.OutputTuple,
    SwapFinalizedEvent.OutputObject
  >;

  filters: {
    "ConfidentialToERC20Swap(address,uint256)": TypedContractEvent<
      ConfidentialToERC20SwapEvent.InputTuple,
      ConfidentialToERC20SwapEvent.OutputTuple,
      ConfidentialToERC20SwapEvent.OutputObject
    >;
    ConfidentialToERC20Swap: TypedContractEvent<
      ConfidentialToERC20SwapEvent.InputTuple,
      ConfidentialToERC20SwapEvent.OutputTuple,
      ConfidentialToERC20SwapEvent.OutputObject
    >;

    "ERC20ToConfidentialSwap(address,uint256)": TypedContractEvent<
      ERC20ToConfidentialSwapEvent.InputTuple,
      ERC20ToConfidentialSwapEvent.OutputTuple,
      ERC20ToConfidentialSwapEvent.OutputObject
    >;
    ERC20ToConfidentialSwap: TypedContractEvent<
      ERC20ToConfidentialSwapEvent.InputTuple,
      ERC20ToConfidentialSwapEvent.OutputTuple,
      ERC20ToConfidentialSwapEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SwapFinalized(uint256,address,uint256)": TypedContractEvent<
      SwapFinalizedEvent.InputTuple,
      SwapFinalizedEvent.OutputTuple,
      SwapFinalizedEvent.OutputObject
    >;
    SwapFinalized: TypedContractEvent<
      SwapFinalizedEvent.InputTuple,
      SwapFinalizedEvent.OutputTuple,
      SwapFinalizedEvent.OutputObject
    >;
  };
}
