/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ErrorsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ALREADY_INITIALIZED"
      | "ASSET_ALREADY_INITIALIZED"
      | "ASSET_NOT_INITIALIZED"
      | "BORROWING_NOT_ENABLED"
      | "BORROW_CAP_EXCEEDED"
      | "DEBT_AMOUNT_EXCEEDS_BALANCE"
      | "INSUFFICIENT_BALANCE"
      | "INSUFFICIENT_COLLATERAL"
      | "INVALID_AMOUNT"
      | "INVALID_ASSET"
      | "INVALID_BASE_RATE"
      | "INVALID_CLOSE_FACTOR"
      | "INVALID_COLLATERAL_FACTOR"
      | "INVALID_INPUT_PROOF"
      | "INVALID_INTEREST_RATE_STRATEGY"
      | "INVALID_JUMP_MULTIPLIER"
      | "INVALID_KINK"
      | "INVALID_LIQUIDATION_BONUS"
      | "INVALID_LIQUIDATION_THRESHOLD"
      | "INVALID_MULTIPLIER"
      | "INVALID_PRICE"
      | "INVALID_RESERVE_CONFIGURATION"
      | "INVALID_RESERVE_FACTOR"
      | "INVALID_TIMESTAMP"
      | "INVALID_USER_POSITION"
      | "LIQUIDATION_AMOUNT_TOO_HIGH"
      | "NOT_INITIALIZED"
      | "ONLY_POOL_ADMIN"
      | "ONLY_PRICE_FEED"
      | "ORACLE_NOT_SET"
      | "PRICE_NOT_SET"
      | "PROTOCOL_PAUSED"
      | "RESERVE_ALREADY_INITIALIZED"
      | "RESERVE_NOT_ACTIVE"
      | "SUPPLY_CAP_EXCEEDED"
      | "UNAUTHORIZED_ACCESS"
      | "USER_POSITION_ALREADY_INITIALIZED"
      | "USER_POSITION_NOT_INITIALIZED"
      | "ZERO_ADDRESS"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "ALREADY_INITIALIZED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ASSET_ALREADY_INITIALIZED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ASSET_NOT_INITIALIZED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BORROWING_NOT_ENABLED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BORROW_CAP_EXCEEDED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEBT_AMOUNT_EXCEEDS_BALANCE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INSUFFICIENT_BALANCE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INSUFFICIENT_COLLATERAL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVALID_AMOUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVALID_ASSET",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVALID_BASE_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVALID_CLOSE_FACTOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVALID_COLLATERAL_FACTOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVALID_INPUT_PROOF",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVALID_INTEREST_RATE_STRATEGY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVALID_JUMP_MULTIPLIER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVALID_KINK",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVALID_LIQUIDATION_BONUS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVALID_LIQUIDATION_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVALID_MULTIPLIER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVALID_PRICE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVALID_RESERVE_CONFIGURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVALID_RESERVE_FACTOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVALID_TIMESTAMP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVALID_USER_POSITION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LIQUIDATION_AMOUNT_TOO_HIGH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "NOT_INITIALIZED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ONLY_POOL_ADMIN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ONLY_PRICE_FEED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ORACLE_NOT_SET",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PRICE_NOT_SET",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROTOCOL_PAUSED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RESERVE_ALREADY_INITIALIZED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RESERVE_NOT_ACTIVE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SUPPLY_CAP_EXCEEDED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UNAUTHORIZED_ACCESS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "USER_POSITION_ALREADY_INITIALIZED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "USER_POSITION_NOT_INITIALIZED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ZERO_ADDRESS",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "ALREADY_INITIALIZED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ASSET_ALREADY_INITIALIZED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ASSET_NOT_INITIALIZED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BORROWING_NOT_ENABLED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BORROW_CAP_EXCEEDED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEBT_AMOUNT_EXCEEDS_BALANCE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INSUFFICIENT_BALANCE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INSUFFICIENT_COLLATERAL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVALID_AMOUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVALID_ASSET",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVALID_BASE_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVALID_CLOSE_FACTOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVALID_COLLATERAL_FACTOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVALID_INPUT_PROOF",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVALID_INTEREST_RATE_STRATEGY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVALID_JUMP_MULTIPLIER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVALID_KINK",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVALID_LIQUIDATION_BONUS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVALID_LIQUIDATION_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVALID_MULTIPLIER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVALID_PRICE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVALID_RESERVE_CONFIGURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVALID_RESERVE_FACTOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVALID_TIMESTAMP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVALID_USER_POSITION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LIQUIDATION_AMOUNT_TOO_HIGH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "NOT_INITIALIZED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ONLY_POOL_ADMIN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ONLY_PRICE_FEED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ORACLE_NOT_SET",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PRICE_NOT_SET",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PROTOCOL_PAUSED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RESERVE_ALREADY_INITIALIZED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RESERVE_NOT_ACTIVE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SUPPLY_CAP_EXCEEDED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UNAUTHORIZED_ACCESS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "USER_POSITION_ALREADY_INITIALIZED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "USER_POSITION_NOT_INITIALIZED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ZERO_ADDRESS",
    data: BytesLike
  ): Result;
}

export interface Errors extends BaseContract {
  connect(runner?: ContractRunner | null): Errors;
  waitForDeployment(): Promise<this>;

  interface: ErrorsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ALREADY_INITIALIZED: TypedContractMethod<[], [string], "view">;

  ASSET_ALREADY_INITIALIZED: TypedContractMethod<[], [string], "view">;

  ASSET_NOT_INITIALIZED: TypedContractMethod<[], [string], "view">;

  BORROWING_NOT_ENABLED: TypedContractMethod<[], [string], "view">;

  BORROW_CAP_EXCEEDED: TypedContractMethod<[], [string], "view">;

  DEBT_AMOUNT_EXCEEDS_BALANCE: TypedContractMethod<[], [string], "view">;

  INSUFFICIENT_BALANCE: TypedContractMethod<[], [string], "view">;

  INSUFFICIENT_COLLATERAL: TypedContractMethod<[], [string], "view">;

  INVALID_AMOUNT: TypedContractMethod<[], [string], "view">;

  INVALID_ASSET: TypedContractMethod<[], [string], "view">;

  INVALID_BASE_RATE: TypedContractMethod<[], [string], "view">;

  INVALID_CLOSE_FACTOR: TypedContractMethod<[], [string], "view">;

  INVALID_COLLATERAL_FACTOR: TypedContractMethod<[], [string], "view">;

  INVALID_INPUT_PROOF: TypedContractMethod<[], [string], "view">;

  INVALID_INTEREST_RATE_STRATEGY: TypedContractMethod<[], [string], "view">;

  INVALID_JUMP_MULTIPLIER: TypedContractMethod<[], [string], "view">;

  INVALID_KINK: TypedContractMethod<[], [string], "view">;

  INVALID_LIQUIDATION_BONUS: TypedContractMethod<[], [string], "view">;

  INVALID_LIQUIDATION_THRESHOLD: TypedContractMethod<[], [string], "view">;

  INVALID_MULTIPLIER: TypedContractMethod<[], [string], "view">;

  INVALID_PRICE: TypedContractMethod<[], [string], "view">;

  INVALID_RESERVE_CONFIGURATION: TypedContractMethod<[], [string], "view">;

  INVALID_RESERVE_FACTOR: TypedContractMethod<[], [string], "view">;

  INVALID_TIMESTAMP: TypedContractMethod<[], [string], "view">;

  INVALID_USER_POSITION: TypedContractMethod<[], [string], "view">;

  LIQUIDATION_AMOUNT_TOO_HIGH: TypedContractMethod<[], [string], "view">;

  NOT_INITIALIZED: TypedContractMethod<[], [string], "view">;

  ONLY_POOL_ADMIN: TypedContractMethod<[], [string], "view">;

  ONLY_PRICE_FEED: TypedContractMethod<[], [string], "view">;

  ORACLE_NOT_SET: TypedContractMethod<[], [string], "view">;

  PRICE_NOT_SET: TypedContractMethod<[], [string], "view">;

  PROTOCOL_PAUSED: TypedContractMethod<[], [string], "view">;

  RESERVE_ALREADY_INITIALIZED: TypedContractMethod<[], [string], "view">;

  RESERVE_NOT_ACTIVE: TypedContractMethod<[], [string], "view">;

  SUPPLY_CAP_EXCEEDED: TypedContractMethod<[], [string], "view">;

  UNAUTHORIZED_ACCESS: TypedContractMethod<[], [string], "view">;

  USER_POSITION_ALREADY_INITIALIZED: TypedContractMethod<[], [string], "view">;

  USER_POSITION_NOT_INITIALIZED: TypedContractMethod<[], [string], "view">;

  ZERO_ADDRESS: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ALREADY_INITIALIZED"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ASSET_ALREADY_INITIALIZED"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ASSET_NOT_INITIALIZED"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "BORROWING_NOT_ENABLED"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "BORROW_CAP_EXCEEDED"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEBT_AMOUNT_EXCEEDS_BALANCE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INSUFFICIENT_BALANCE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INSUFFICIENT_COLLATERAL"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INVALID_AMOUNT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INVALID_ASSET"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INVALID_BASE_RATE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INVALID_CLOSE_FACTOR"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INVALID_COLLATERAL_FACTOR"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INVALID_INPUT_PROOF"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INVALID_INTEREST_RATE_STRATEGY"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INVALID_JUMP_MULTIPLIER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INVALID_KINK"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INVALID_LIQUIDATION_BONUS"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INVALID_LIQUIDATION_THRESHOLD"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INVALID_MULTIPLIER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INVALID_PRICE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INVALID_RESERVE_CONFIGURATION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INVALID_RESERVE_FACTOR"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INVALID_TIMESTAMP"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INVALID_USER_POSITION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "LIQUIDATION_AMOUNT_TOO_HIGH"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "NOT_INITIALIZED"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ONLY_POOL_ADMIN"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ONLY_PRICE_FEED"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ORACLE_NOT_SET"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PRICE_NOT_SET"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PROTOCOL_PAUSED"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "RESERVE_ALREADY_INITIALIZED"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "RESERVE_NOT_ACTIVE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SUPPLY_CAP_EXCEEDED"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "UNAUTHORIZED_ACCESS"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "USER_POSITION_ALREADY_INITIALIZED"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "USER_POSITION_NOT_INITIALIZED"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ZERO_ADDRESS"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
