/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace Types {
  export type ConfidentialReserveStruct = {
    underlyingAsset: AddressLike;
    totalSupplied: BytesLike;
    totalBorrowed: BytesLike;
    availableLiquidity: BytesLike;
    lastUpdateTimestamp: BigNumberish;
    active: boolean;
    borrowingEnabled: boolean;
    isCollateral: boolean;
    isPaused: boolean;
    collateralFactor: BigNumberish;
    supplyCap: BigNumberish;
    borrowCap: BigNumberish;
    decimals: BigNumberish;
  };

  export type ConfidentialReserveStructOutput = [
    underlyingAsset: string,
    totalSupplied: string,
    totalBorrowed: string,
    availableLiquidity: string,
    lastUpdateTimestamp: bigint,
    active: boolean,
    borrowingEnabled: boolean,
    isCollateral: boolean,
    isPaused: boolean,
    collateralFactor: bigint,
    supplyCap: bigint,
    borrowCap: bigint,
    decimals: bigint
  ] & {
    underlyingAsset: string;
    totalSupplied: string;
    totalBorrowed: string;
    availableLiquidity: string;
    lastUpdateTimestamp: bigint;
    active: boolean;
    borrowingEnabled: boolean;
    isCollateral: boolean;
    isPaused: boolean;
    collateralFactor: bigint;
    supplyCap: bigint;
    borrowCap: bigint;
    decimals: bigint;
  };
}

export interface ConfidentialPoolConfiguratorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "aclManager"
      | "getReserveConfig"
      | "initReserve"
      | "lendingPool"
      | "owner"
      | "pauseReserve"
      | "renounceOwnership"
      | "reserves"
      | "setBorrowCap"
      | "setCollateralFactor"
      | "setLendingPool"
      | "setReserveActive"
      | "setReserveBorrowing"
      | "setReserveCollateral"
      | "setSupplyCap"
      | "transferOwnership"
      | "unpauseReserve"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BorrowCapUpdated"
      | "CollateralFactorUpdated"
      | "OwnershipTransferred"
      | "ReserveActiveChanged"
      | "ReserveBorrowingChanged"
      | "ReserveCollateralChanged"
      | "ReserveInitialized"
      | "ReservePaused"
      | "ReserveUnpaused"
      | "SupplyCapUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "aclManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getReserveConfig",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initReserve",
    values: [AddressLike, boolean, boolean, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lendingPool",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pauseReserve",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reserves",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setBorrowCap",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setCollateralFactor",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setLendingPool",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setReserveActive",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setReserveBorrowing",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setReserveCollateral",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setSupplyCap",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unpauseReserve",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "aclManager", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getReserveConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lendingPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pauseReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reserves", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setBorrowCap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCollateralFactor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLendingPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReserveActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReserveBorrowing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReserveCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSupplyCap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unpauseReserve",
    data: BytesLike
  ): Result;
}

export namespace BorrowCapUpdatedEvent {
  export type InputTuple = [asset: AddressLike, cap: BigNumberish];
  export type OutputTuple = [asset: string, cap: bigint];
  export interface OutputObject {
    asset: string;
    cap: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CollateralFactorUpdatedEvent {
  export type InputTuple = [asset: AddressLike, factor: BigNumberish];
  export type OutputTuple = [asset: string, factor: bigint];
  export interface OutputObject {
    asset: string;
    factor: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReserveActiveChangedEvent {
  export type InputTuple = [asset: AddressLike, active: boolean];
  export type OutputTuple = [asset: string, active: boolean];
  export interface OutputObject {
    asset: string;
    active: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReserveBorrowingChangedEvent {
  export type InputTuple = [asset: AddressLike, enabled: boolean];
  export type OutputTuple = [asset: string, enabled: boolean];
  export interface OutputObject {
    asset: string;
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReserveCollateralChangedEvent {
  export type InputTuple = [asset: AddressLike, enabled: boolean];
  export type OutputTuple = [asset: string, enabled: boolean];
  export interface OutputObject {
    asset: string;
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReserveInitializedEvent {
  export type InputTuple = [
    asset: AddressLike,
    borrowingEnabled: boolean,
    isCollateral: boolean
  ];
  export type OutputTuple = [
    asset: string,
    borrowingEnabled: boolean,
    isCollateral: boolean
  ];
  export interface OutputObject {
    asset: string;
    borrowingEnabled: boolean;
    isCollateral: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReservePausedEvent {
  export type InputTuple = [asset: AddressLike];
  export type OutputTuple = [asset: string];
  export interface OutputObject {
    asset: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReserveUnpausedEvent {
  export type InputTuple = [asset: AddressLike];
  export type OutputTuple = [asset: string];
  export interface OutputObject {
    asset: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SupplyCapUpdatedEvent {
  export type InputTuple = [asset: AddressLike, cap: BigNumberish];
  export type OutputTuple = [asset: string, cap: bigint];
  export interface OutputObject {
    asset: string;
    cap: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ConfidentialPoolConfigurator extends BaseContract {
  connect(runner?: ContractRunner | null): ConfidentialPoolConfigurator;
  waitForDeployment(): Promise<this>;

  interface: ConfidentialPoolConfiguratorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  aclManager: TypedContractMethod<[], [string], "view">;

  getReserveConfig: TypedContractMethod<
    [asset: AddressLike],
    [Types.ConfidentialReserveStructOutput],
    "view"
  >;

  initReserve: TypedContractMethod<
    [
      asset: AddressLike,
      borrowingEnabled: boolean,
      isCollateral: boolean,
      collateralFactor: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  lendingPool: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pauseReserve: TypedContractMethod<[asset: AddressLike], [void], "nonpayable">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  reserves: TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        boolean,
        boolean,
        boolean,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        underlyingAsset: string;
        totalSupplied: string;
        totalBorrowed: string;
        availableLiquidity: string;
        lastUpdateTimestamp: bigint;
        active: boolean;
        borrowingEnabled: boolean;
        isCollateral: boolean;
        isPaused: boolean;
        collateralFactor: bigint;
        supplyCap: bigint;
        borrowCap: bigint;
        decimals: bigint;
      }
    ],
    "view"
  >;

  setBorrowCap: TypedContractMethod<
    [asset: AddressLike, cap: BigNumberish],
    [void],
    "nonpayable"
  >;

  setCollateralFactor: TypedContractMethod<
    [asset: AddressLike, factor: BigNumberish],
    [void],
    "nonpayable"
  >;

  setLendingPool: TypedContractMethod<
    [_lendingPool: AddressLike],
    [void],
    "nonpayable"
  >;

  setReserveActive: TypedContractMethod<
    [asset: AddressLike, active: boolean],
    [void],
    "nonpayable"
  >;

  setReserveBorrowing: TypedContractMethod<
    [asset: AddressLike, enabled: boolean],
    [void],
    "nonpayable"
  >;

  setReserveCollateral: TypedContractMethod<
    [asset: AddressLike, enabled: boolean],
    [void],
    "nonpayable"
  >;

  setSupplyCap: TypedContractMethod<
    [asset: AddressLike, cap: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpauseReserve: TypedContractMethod<
    [asset: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "aclManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getReserveConfig"
  ): TypedContractMethod<
    [asset: AddressLike],
    [Types.ConfidentialReserveStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "initReserve"
  ): TypedContractMethod<
    [
      asset: AddressLike,
      borrowingEnabled: boolean,
      isCollateral: boolean,
      collateralFactor: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lendingPool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pauseReserve"
  ): TypedContractMethod<[asset: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reserves"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        boolean,
        boolean,
        boolean,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        underlyingAsset: string;
        totalSupplied: string;
        totalBorrowed: string;
        availableLiquidity: string;
        lastUpdateTimestamp: bigint;
        active: boolean;
        borrowingEnabled: boolean;
        isCollateral: boolean;
        isPaused: boolean;
        collateralFactor: bigint;
        supplyCap: bigint;
        borrowCap: bigint;
        decimals: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setBorrowCap"
  ): TypedContractMethod<
    [asset: AddressLike, cap: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setCollateralFactor"
  ): TypedContractMethod<
    [asset: AddressLike, factor: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setLendingPool"
  ): TypedContractMethod<[_lendingPool: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setReserveActive"
  ): TypedContractMethod<
    [asset: AddressLike, active: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setReserveBorrowing"
  ): TypedContractMethod<
    [asset: AddressLike, enabled: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setReserveCollateral"
  ): TypedContractMethod<
    [asset: AddressLike, enabled: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSupplyCap"
  ): TypedContractMethod<
    [asset: AddressLike, cap: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpauseReserve"
  ): TypedContractMethod<[asset: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "BorrowCapUpdated"
  ): TypedContractEvent<
    BorrowCapUpdatedEvent.InputTuple,
    BorrowCapUpdatedEvent.OutputTuple,
    BorrowCapUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "CollateralFactorUpdated"
  ): TypedContractEvent<
    CollateralFactorUpdatedEvent.InputTuple,
    CollateralFactorUpdatedEvent.OutputTuple,
    CollateralFactorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ReserveActiveChanged"
  ): TypedContractEvent<
    ReserveActiveChangedEvent.InputTuple,
    ReserveActiveChangedEvent.OutputTuple,
    ReserveActiveChangedEvent.OutputObject
  >;
  getEvent(
    key: "ReserveBorrowingChanged"
  ): TypedContractEvent<
    ReserveBorrowingChangedEvent.InputTuple,
    ReserveBorrowingChangedEvent.OutputTuple,
    ReserveBorrowingChangedEvent.OutputObject
  >;
  getEvent(
    key: "ReserveCollateralChanged"
  ): TypedContractEvent<
    ReserveCollateralChangedEvent.InputTuple,
    ReserveCollateralChangedEvent.OutputTuple,
    ReserveCollateralChangedEvent.OutputObject
  >;
  getEvent(
    key: "ReserveInitialized"
  ): TypedContractEvent<
    ReserveInitializedEvent.InputTuple,
    ReserveInitializedEvent.OutputTuple,
    ReserveInitializedEvent.OutputObject
  >;
  getEvent(
    key: "ReservePaused"
  ): TypedContractEvent<
    ReservePausedEvent.InputTuple,
    ReservePausedEvent.OutputTuple,
    ReservePausedEvent.OutputObject
  >;
  getEvent(
    key: "ReserveUnpaused"
  ): TypedContractEvent<
    ReserveUnpausedEvent.InputTuple,
    ReserveUnpausedEvent.OutputTuple,
    ReserveUnpausedEvent.OutputObject
  >;
  getEvent(
    key: "SupplyCapUpdated"
  ): TypedContractEvent<
    SupplyCapUpdatedEvent.InputTuple,
    SupplyCapUpdatedEvent.OutputTuple,
    SupplyCapUpdatedEvent.OutputObject
  >;

  filters: {
    "BorrowCapUpdated(address,uint64)": TypedContractEvent<
      BorrowCapUpdatedEvent.InputTuple,
      BorrowCapUpdatedEvent.OutputTuple,
      BorrowCapUpdatedEvent.OutputObject
    >;
    BorrowCapUpdated: TypedContractEvent<
      BorrowCapUpdatedEvent.InputTuple,
      BorrowCapUpdatedEvent.OutputTuple,
      BorrowCapUpdatedEvent.OutputObject
    >;

    "CollateralFactorUpdated(address,uint64)": TypedContractEvent<
      CollateralFactorUpdatedEvent.InputTuple,
      CollateralFactorUpdatedEvent.OutputTuple,
      CollateralFactorUpdatedEvent.OutputObject
    >;
    CollateralFactorUpdated: TypedContractEvent<
      CollateralFactorUpdatedEvent.InputTuple,
      CollateralFactorUpdatedEvent.OutputTuple,
      CollateralFactorUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ReserveActiveChanged(address,bool)": TypedContractEvent<
      ReserveActiveChangedEvent.InputTuple,
      ReserveActiveChangedEvent.OutputTuple,
      ReserveActiveChangedEvent.OutputObject
    >;
    ReserveActiveChanged: TypedContractEvent<
      ReserveActiveChangedEvent.InputTuple,
      ReserveActiveChangedEvent.OutputTuple,
      ReserveActiveChangedEvent.OutputObject
    >;

    "ReserveBorrowingChanged(address,bool)": TypedContractEvent<
      ReserveBorrowingChangedEvent.InputTuple,
      ReserveBorrowingChangedEvent.OutputTuple,
      ReserveBorrowingChangedEvent.OutputObject
    >;
    ReserveBorrowingChanged: TypedContractEvent<
      ReserveBorrowingChangedEvent.InputTuple,
      ReserveBorrowingChangedEvent.OutputTuple,
      ReserveBorrowingChangedEvent.OutputObject
    >;

    "ReserveCollateralChanged(address,bool)": TypedContractEvent<
      ReserveCollateralChangedEvent.InputTuple,
      ReserveCollateralChangedEvent.OutputTuple,
      ReserveCollateralChangedEvent.OutputObject
    >;
    ReserveCollateralChanged: TypedContractEvent<
      ReserveCollateralChangedEvent.InputTuple,
      ReserveCollateralChangedEvent.OutputTuple,
      ReserveCollateralChangedEvent.OutputObject
    >;

    "ReserveInitialized(address,bool,bool)": TypedContractEvent<
      ReserveInitializedEvent.InputTuple,
      ReserveInitializedEvent.OutputTuple,
      ReserveInitializedEvent.OutputObject
    >;
    ReserveInitialized: TypedContractEvent<
      ReserveInitializedEvent.InputTuple,
      ReserveInitializedEvent.OutputTuple,
      ReserveInitializedEvent.OutputObject
    >;

    "ReservePaused(address)": TypedContractEvent<
      ReservePausedEvent.InputTuple,
      ReservePausedEvent.OutputTuple,
      ReservePausedEvent.OutputObject
    >;
    ReservePaused: TypedContractEvent<
      ReservePausedEvent.InputTuple,
      ReservePausedEvent.OutputTuple,
      ReservePausedEvent.OutputObject
    >;

    "ReserveUnpaused(address)": TypedContractEvent<
      ReserveUnpausedEvent.InputTuple,
      ReserveUnpausedEvent.OutputTuple,
      ReserveUnpausedEvent.OutputObject
    >;
    ReserveUnpaused: TypedContractEvent<
      ReserveUnpausedEvent.InputTuple,
      ReserveUnpausedEvent.OutputTuple,
      ReserveUnpausedEvent.OutputObject
    >;

    "SupplyCapUpdated(address,uint64)": TypedContractEvent<
      SupplyCapUpdatedEvent.InputTuple,
      SupplyCapUpdatedEvent.OutputTuple,
      SupplyCapUpdatedEvent.OutputObject
    >;
    SupplyCapUpdated: TypedContractEvent<
      SupplyCapUpdatedEvent.InputTuple,
      SupplyCapUpdatedEvent.OutputTuple,
      SupplyCapUpdatedEvent.OutputObject
    >;
  };
}
