/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ErrorsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ALREADY_INITIALIZED"
      | "ASSET_ALREADY_INITIALIZED"
      | "ASSET_NOT_INITIALIZED"
      | "BORROWING_NOT_ENABLED"
      | "BORROW_AMOUNT_TOO_LOW"
      | "BORROW_CAP_EXCEEDED"
      | "DEBT_AMOUNT_EXCEEDS_BALANCE"
      | "INSUFFICIENT_BALANCE"
      | "INSUFFICIENT_COLLATERAL"
      | "INVALID_AMOUNT"
      | "INVALID_ASSET"
      | "INVALID_ASSET_DECIMALS"
      | "INVALID_BASE_RATE"
      | "INVALID_CLOSE_FACTOR"
      | "INVALID_COLLATERAL"
      | "INVALID_COLLATERAL_FACTOR"
      | "INVALID_DEBT_REPAYMENT"
      | "INVALID_INPUT_PROOF"
      | "INVALID_INTEREST_RATE_STRATEGY"
      | "INVALID_JUMP_MULTIPLIER"
      | "INVALID_KINK"
      | "INVALID_LIQUIDATION_BONUS"
      | "INVALID_LIQUIDATION_THRESHOLD"
      | "INVALID_LIQUIDATOR"
      | "INVALID_MULTIPLIER"
      | "INVALID_PRICE"
      | "INVALID_RESERVE_CONFIGURATION"
      | "INVALID_RESERVE_FACTOR"
      | "INVALID_TIMESTAMP"
      | "INVALID_USER_POSITION"
      | "LIQUIDATION_AMOUNT_TOO_HIGH"
      | "LIQUIDATION_NOT_ALLOWED"
      | "MULTIPLE_DEBTS_NOT_ALLOWED"
      | "NOT_INITIALIZED"
      | "NOT_THE_DESIGNATED_COLLATERAL"
      | "NO_DEBT_POSITION"
      | "ONLY_EMERGENCY_ADMIN"
      | "ONLY_POOL_ADMIN"
      | "ONLY_POOL_CONFIGURATOR"
      | "ONLY_PRICE_FEED"
      | "ORACLE_NOT_SET"
      | "ORACLE_PRICE_ZERO"
      | "PRICE_NOT_SET"
      | "PROTOCOL_ALREADY_PAUSED"
      | "PROTOCOL_NOT_PAUSED"
      | "PROTOCOL_PAUSED"
      | "REPAY_AMOUNT_EXCEEDS_DEBT"
      | "REPAY_AMOUNT_TOO_LOW"
      | "RESERVE_ALREADY_INITIALIZED"
      | "RESERVE_NOT_ACTIVE"
      | "RESERVE_NOT_INITIALIZED"
      | "SINGLE_COLLATERAL_ONLY"
      | "SUPPLY_AMOUNT_TOO_LOW"
      | "SUPPLY_CAP_EXCEEDED"
      | "USER_POSITION_ALREADY_INITIALIZED"
      | "USER_POSITION_NOT_INITIALIZED"
      | "WITHDRAW_AMOUNT_TOO_LOW"
      | "ZERO_ADDRESS"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "ALREADY_INITIALIZED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ASSET_ALREADY_INITIALIZED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ASSET_NOT_INITIALIZED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BORROWING_NOT_ENABLED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BORROW_AMOUNT_TOO_LOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BORROW_CAP_EXCEEDED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEBT_AMOUNT_EXCEEDS_BALANCE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INSUFFICIENT_BALANCE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INSUFFICIENT_COLLATERAL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVALID_AMOUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVALID_ASSET",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVALID_ASSET_DECIMALS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVALID_BASE_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVALID_CLOSE_FACTOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVALID_COLLATERAL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVALID_COLLATERAL_FACTOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVALID_DEBT_REPAYMENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVALID_INPUT_PROOF",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVALID_INTEREST_RATE_STRATEGY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVALID_JUMP_MULTIPLIER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVALID_KINK",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVALID_LIQUIDATION_BONUS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVALID_LIQUIDATION_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVALID_LIQUIDATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVALID_MULTIPLIER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVALID_PRICE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVALID_RESERVE_CONFIGURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVALID_RESERVE_FACTOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVALID_TIMESTAMP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVALID_USER_POSITION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LIQUIDATION_AMOUNT_TOO_HIGH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LIQUIDATION_NOT_ALLOWED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MULTIPLE_DEBTS_NOT_ALLOWED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "NOT_INITIALIZED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "NOT_THE_DESIGNATED_COLLATERAL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "NO_DEBT_POSITION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ONLY_EMERGENCY_ADMIN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ONLY_POOL_ADMIN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ONLY_POOL_CONFIGURATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ONLY_PRICE_FEED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ORACLE_NOT_SET",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ORACLE_PRICE_ZERO",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PRICE_NOT_SET",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROTOCOL_ALREADY_PAUSED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROTOCOL_NOT_PAUSED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROTOCOL_PAUSED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REPAY_AMOUNT_EXCEEDS_DEBT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REPAY_AMOUNT_TOO_LOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RESERVE_ALREADY_INITIALIZED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RESERVE_NOT_ACTIVE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RESERVE_NOT_INITIALIZED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SINGLE_COLLATERAL_ONLY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SUPPLY_AMOUNT_TOO_LOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SUPPLY_CAP_EXCEEDED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "USER_POSITION_ALREADY_INITIALIZED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "USER_POSITION_NOT_INITIALIZED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WITHDRAW_AMOUNT_TOO_LOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ZERO_ADDRESS",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "ALREADY_INITIALIZED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ASSET_ALREADY_INITIALIZED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ASSET_NOT_INITIALIZED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BORROWING_NOT_ENABLED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BORROW_AMOUNT_TOO_LOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BORROW_CAP_EXCEEDED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEBT_AMOUNT_EXCEEDS_BALANCE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INSUFFICIENT_BALANCE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INSUFFICIENT_COLLATERAL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVALID_AMOUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVALID_ASSET",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVALID_ASSET_DECIMALS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVALID_BASE_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVALID_CLOSE_FACTOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVALID_COLLATERAL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVALID_COLLATERAL_FACTOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVALID_DEBT_REPAYMENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVALID_INPUT_PROOF",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVALID_INTEREST_RATE_STRATEGY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVALID_JUMP_MULTIPLIER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVALID_KINK",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVALID_LIQUIDATION_BONUS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVALID_LIQUIDATION_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVALID_LIQUIDATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVALID_MULTIPLIER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVALID_PRICE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVALID_RESERVE_CONFIGURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVALID_RESERVE_FACTOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVALID_TIMESTAMP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVALID_USER_POSITION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LIQUIDATION_AMOUNT_TOO_HIGH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LIQUIDATION_NOT_ALLOWED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MULTIPLE_DEBTS_NOT_ALLOWED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "NOT_INITIALIZED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "NOT_THE_DESIGNATED_COLLATERAL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "NO_DEBT_POSITION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ONLY_EMERGENCY_ADMIN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ONLY_POOL_ADMIN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ONLY_POOL_CONFIGURATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ONLY_PRICE_FEED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ORACLE_NOT_SET",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ORACLE_PRICE_ZERO",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PRICE_NOT_SET",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PROTOCOL_ALREADY_PAUSED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PROTOCOL_NOT_PAUSED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PROTOCOL_PAUSED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REPAY_AMOUNT_EXCEEDS_DEBT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REPAY_AMOUNT_TOO_LOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RESERVE_ALREADY_INITIALIZED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RESERVE_NOT_ACTIVE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RESERVE_NOT_INITIALIZED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SINGLE_COLLATERAL_ONLY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SUPPLY_AMOUNT_TOO_LOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SUPPLY_CAP_EXCEEDED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "USER_POSITION_ALREADY_INITIALIZED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "USER_POSITION_NOT_INITIALIZED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "WITHDRAW_AMOUNT_TOO_LOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ZERO_ADDRESS",
    data: BytesLike
  ): Result;
}

export interface Errors extends BaseContract {
  connect(runner?: ContractRunner | null): Errors;
  waitForDeployment(): Promise<this>;

  interface: ErrorsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ALREADY_INITIALIZED: TypedContractMethod<[], [string], "view">;

  ASSET_ALREADY_INITIALIZED: TypedContractMethod<[], [string], "view">;

  ASSET_NOT_INITIALIZED: TypedContractMethod<[], [string], "view">;

  BORROWING_NOT_ENABLED: TypedContractMethod<[], [string], "view">;

  BORROW_AMOUNT_TOO_LOW: TypedContractMethod<[], [string], "view">;

  BORROW_CAP_EXCEEDED: TypedContractMethod<[], [string], "view">;

  DEBT_AMOUNT_EXCEEDS_BALANCE: TypedContractMethod<[], [string], "view">;

  INSUFFICIENT_BALANCE: TypedContractMethod<[], [string], "view">;

  INSUFFICIENT_COLLATERAL: TypedContractMethod<[], [string], "view">;

  INVALID_AMOUNT: TypedContractMethod<[], [string], "view">;

  INVALID_ASSET: TypedContractMethod<[], [string], "view">;

  INVALID_ASSET_DECIMALS: TypedContractMethod<[], [string], "view">;

  INVALID_BASE_RATE: TypedContractMethod<[], [string], "view">;

  INVALID_CLOSE_FACTOR: TypedContractMethod<[], [string], "view">;

  INVALID_COLLATERAL: TypedContractMethod<[], [string], "view">;

  INVALID_COLLATERAL_FACTOR: TypedContractMethod<[], [string], "view">;

  INVALID_DEBT_REPAYMENT: TypedContractMethod<[], [string], "view">;

  INVALID_INPUT_PROOF: TypedContractMethod<[], [string], "view">;

  INVALID_INTEREST_RATE_STRATEGY: TypedContractMethod<[], [string], "view">;

  INVALID_JUMP_MULTIPLIER: TypedContractMethod<[], [string], "view">;

  INVALID_KINK: TypedContractMethod<[], [string], "view">;

  INVALID_LIQUIDATION_BONUS: TypedContractMethod<[], [string], "view">;

  INVALID_LIQUIDATION_THRESHOLD: TypedContractMethod<[], [string], "view">;

  INVALID_LIQUIDATOR: TypedContractMethod<[], [string], "view">;

  INVALID_MULTIPLIER: TypedContractMethod<[], [string], "view">;

  INVALID_PRICE: TypedContractMethod<[], [string], "view">;

  INVALID_RESERVE_CONFIGURATION: TypedContractMethod<[], [string], "view">;

  INVALID_RESERVE_FACTOR: TypedContractMethod<[], [string], "view">;

  INVALID_TIMESTAMP: TypedContractMethod<[], [string], "view">;

  INVALID_USER_POSITION: TypedContractMethod<[], [string], "view">;

  LIQUIDATION_AMOUNT_TOO_HIGH: TypedContractMethod<[], [string], "view">;

  LIQUIDATION_NOT_ALLOWED: TypedContractMethod<[], [string], "view">;

  MULTIPLE_DEBTS_NOT_ALLOWED: TypedContractMethod<[], [string], "view">;

  NOT_INITIALIZED: TypedContractMethod<[], [string], "view">;

  NOT_THE_DESIGNATED_COLLATERAL: TypedContractMethod<[], [string], "view">;

  NO_DEBT_POSITION: TypedContractMethod<[], [string], "view">;

  ONLY_EMERGENCY_ADMIN: TypedContractMethod<[], [string], "view">;

  ONLY_POOL_ADMIN: TypedContractMethod<[], [string], "view">;

  ONLY_POOL_CONFIGURATOR: TypedContractMethod<[], [string], "view">;

  ONLY_PRICE_FEED: TypedContractMethod<[], [string], "view">;

  ORACLE_NOT_SET: TypedContractMethod<[], [string], "view">;

  ORACLE_PRICE_ZERO: TypedContractMethod<[], [string], "view">;

  PRICE_NOT_SET: TypedContractMethod<[], [string], "view">;

  PROTOCOL_ALREADY_PAUSED: TypedContractMethod<[], [string], "view">;

  PROTOCOL_NOT_PAUSED: TypedContractMethod<[], [string], "view">;

  PROTOCOL_PAUSED: TypedContractMethod<[], [string], "view">;

  REPAY_AMOUNT_EXCEEDS_DEBT: TypedContractMethod<[], [string], "view">;

  REPAY_AMOUNT_TOO_LOW: TypedContractMethod<[], [string], "view">;

  RESERVE_ALREADY_INITIALIZED: TypedContractMethod<[], [string], "view">;

  RESERVE_NOT_ACTIVE: TypedContractMethod<[], [string], "view">;

  RESERVE_NOT_INITIALIZED: TypedContractMethod<[], [string], "view">;

  SINGLE_COLLATERAL_ONLY: TypedContractMethod<[], [string], "view">;

  SUPPLY_AMOUNT_TOO_LOW: TypedContractMethod<[], [string], "view">;

  SUPPLY_CAP_EXCEEDED: TypedContractMethod<[], [string], "view">;

  USER_POSITION_ALREADY_INITIALIZED: TypedContractMethod<[], [string], "view">;

  USER_POSITION_NOT_INITIALIZED: TypedContractMethod<[], [string], "view">;

  WITHDRAW_AMOUNT_TOO_LOW: TypedContractMethod<[], [string], "view">;

  ZERO_ADDRESS: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ALREADY_INITIALIZED"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ASSET_ALREADY_INITIALIZED"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ASSET_NOT_INITIALIZED"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "BORROWING_NOT_ENABLED"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "BORROW_AMOUNT_TOO_LOW"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "BORROW_CAP_EXCEEDED"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEBT_AMOUNT_EXCEEDS_BALANCE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INSUFFICIENT_BALANCE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INSUFFICIENT_COLLATERAL"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INVALID_AMOUNT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INVALID_ASSET"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INVALID_ASSET_DECIMALS"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INVALID_BASE_RATE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INVALID_CLOSE_FACTOR"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INVALID_COLLATERAL"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INVALID_COLLATERAL_FACTOR"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INVALID_DEBT_REPAYMENT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INVALID_INPUT_PROOF"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INVALID_INTEREST_RATE_STRATEGY"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INVALID_JUMP_MULTIPLIER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INVALID_KINK"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INVALID_LIQUIDATION_BONUS"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INVALID_LIQUIDATION_THRESHOLD"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INVALID_LIQUIDATOR"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INVALID_MULTIPLIER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INVALID_PRICE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INVALID_RESERVE_CONFIGURATION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INVALID_RESERVE_FACTOR"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INVALID_TIMESTAMP"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INVALID_USER_POSITION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "LIQUIDATION_AMOUNT_TOO_HIGH"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "LIQUIDATION_NOT_ALLOWED"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MULTIPLE_DEBTS_NOT_ALLOWED"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "NOT_INITIALIZED"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "NOT_THE_DESIGNATED_COLLATERAL"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "NO_DEBT_POSITION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ONLY_EMERGENCY_ADMIN"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ONLY_POOL_ADMIN"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ONLY_POOL_CONFIGURATOR"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ONLY_PRICE_FEED"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ORACLE_NOT_SET"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ORACLE_PRICE_ZERO"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PRICE_NOT_SET"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PROTOCOL_ALREADY_PAUSED"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PROTOCOL_NOT_PAUSED"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PROTOCOL_PAUSED"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "REPAY_AMOUNT_EXCEEDS_DEBT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "REPAY_AMOUNT_TOO_LOW"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "RESERVE_ALREADY_INITIALIZED"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "RESERVE_NOT_ACTIVE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "RESERVE_NOT_INITIALIZED"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SINGLE_COLLATERAL_ONLY"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SUPPLY_AMOUNT_TOO_LOW"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SUPPLY_CAP_EXCEEDED"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "USER_POSITION_ALREADY_INITIALIZED"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "USER_POSITION_NOT_INITIALIZED"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "WITHDRAW_AMOUNT_TOO_LOW"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ZERO_ADDRESS"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
