/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IConfidentialFungibleToken__factory } from "./IConfidentialFungibleToken__factory";
export { IConfidentialFungibleTokenReceiver__factory } from "./IConfidentialFungibleTokenReceiver__factory";
