/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace Types {
  export type ConfidentialReserveStruct = {
    underlyingAsset: AddressLike;
    totalSupplied: BytesLike;
    totalBorrowed: BytesLike;
    availableLiquidity: BytesLike;
    lastUpdateTimestamp: BigNumberish;
    active: boolean;
    borrowingEnabled: boolean;
    isCollateral: boolean;
    isPaused: boolean;
    collateralFactor: BigNumberish;
    supplyCap: BigNumberish;
    borrowCap: BigNumberish;
    decimals: BigNumberish;
  };

  export type ConfidentialReserveStructOutput = [
    underlyingAsset: string,
    totalSupplied: string,
    totalBorrowed: string,
    availableLiquidity: string,
    lastUpdateTimestamp: bigint,
    active: boolean,
    borrowingEnabled: boolean,
    isCollateral: boolean,
    isPaused: boolean,
    collateralFactor: bigint,
    supplyCap: bigint,
    borrowCap: bigint,
    decimals: bigint
  ] & {
    underlyingAsset: string;
    totalSupplied: string;
    totalBorrowed: string;
    availableLiquidity: string;
    lastUpdateTimestamp: bigint;
    active: boolean;
    borrowingEnabled: boolean;
    isCollateral: boolean;
    isPaused: boolean;
    collateralFactor: bigint;
    supplyCap: bigint;
    borrowCap: bigint;
    decimals: bigint;
  };

  export type ConfidentialUserPositionStruct = {
    totalBorrowPowerUSD: BytesLike;
    totalDebtUSD: BytesLike;
    totalSuppliedUSD: BytesLike;
    collateralAssets: AddressLike[];
    borrowedAssets: AddressLike[];
    initialized: boolean;
  };

  export type ConfidentialUserPositionStructOutput = [
    totalBorrowPowerUSD: string,
    totalDebtUSD: string,
    totalSuppliedUSD: string,
    collateralAssets: string[],
    borrowedAssets: string[],
    initialized: boolean
  ] & {
    totalBorrowPowerUSD: string;
    totalDebtUSD: string;
    totalSuppliedUSD: string;
    collateralAssets: string[];
    borrowedAssets: string[];
    initialized: boolean;
  };
}

export interface IConfidentialLendingPoolViewInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getReserveData"
      | "getReserveList"
      | "getUserBorrowedBalance"
      | "getUserPosition"
      | "getUserSuppliedBalance"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getReserveData",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getReserveList",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserBorrowedBalance",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserPosition",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserSuppliedBalance",
    values: [AddressLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getReserveData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReserveList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserBorrowedBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserSuppliedBalance",
    data: BytesLike
  ): Result;
}

export interface IConfidentialLendingPoolView extends BaseContract {
  connect(runner?: ContractRunner | null): IConfidentialLendingPoolView;
  waitForDeployment(): Promise<this>;

  interface: IConfidentialLendingPoolViewInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getReserveData: TypedContractMethod<
    [asset: AddressLike],
    [Types.ConfidentialReserveStructOutput],
    "view"
  >;

  getReserveList: TypedContractMethod<[], [string[]], "view">;

  getUserBorrowedBalance: TypedContractMethod<
    [user: AddressLike, asset: AddressLike],
    [string],
    "view"
  >;

  getUserPosition: TypedContractMethod<
    [user: AddressLike],
    [Types.ConfidentialUserPositionStructOutput],
    "view"
  >;

  getUserSuppliedBalance: TypedContractMethod<
    [user: AddressLike, asset: AddressLike],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getReserveData"
  ): TypedContractMethod<
    [asset: AddressLike],
    [Types.ConfidentialReserveStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReserveList"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getUserBorrowedBalance"
  ): TypedContractMethod<
    [user: AddressLike, asset: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserPosition"
  ): TypedContractMethod<
    [user: AddressLike],
    [Types.ConfidentialUserPositionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserSuppliedBalance"
  ): TypedContractMethod<
    [user: AddressLike, asset: AddressLike],
    [string],
    "view"
  >;

  filters: {};
}
