/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  ErrorsLib,
  ErrorsLibInterface,
} from "../../../../contracts/libraries/Errors.sol/ErrorsLib";

const _abi = [
  {
    inputs: [],
    name: "BorrowingNotEnabled",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidDebtRepayment",
    type: "error",
  },
  {
    inputs: [],
    name: "MultipleDebtsNotAllowed",
    type: "error",
  },
  {
    inputs: [],
    name: "NoCollateralEnabled",
    type: "error",
  },
  {
    inputs: [],
    name: "NotTheDesignatedCollateral",
    type: "error",
  },
  {
    inputs: [],
    name: "OnlyEmergencyAdmin",
    type: "error",
  },
  {
    inputs: [],
    name: "OnlyPoolAdmin",
    type: "error",
  },
  {
    inputs: [],
    name: "OnlyPoolConfigurator",
    type: "error",
  },
  {
    inputs: [],
    name: "OraclePriceZero",
    type: "error",
  },
  {
    inputs: [],
    name: "ProtocolAlreadyPaused",
    type: "error",
  },
  {
    inputs: [],
    name: "ProtocolNotPaused",
    type: "error",
  },
  {
    inputs: [],
    name: "ProtocolPaused",
    type: "error",
  },
  {
    inputs: [],
    name: "ReserveAlreadyInitialized",
    type: "error",
  },
  {
    inputs: [],
    name: "ReserveNotActive",
    type: "error",
  },
  {
    inputs: [],
    name: "ReserveNotCollateral",
    type: "error",
  },
  {
    inputs: [],
    name: "ReserveNotInitialized",
    type: "error",
  },
  {
    inputs: [],
    name: "ZeroAddress",
    type: "error",
  },
] as const;

const _bytecode =
  "0x6080806040523460175760109081601c823930815050f35b5f80fdfe5f80fdfea164736f6c634300081b000a";

type ErrorsLibConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ErrorsLibConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ErrorsLib__factory extends ContractFactory {
  constructor(...args: ErrorsLibConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      ErrorsLib & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): ErrorsLib__factory {
    return super.connect(runner) as ErrorsLib__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ErrorsLibInterface {
    return new Interface(_abi) as ErrorsLibInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ErrorsLib {
    return new Contract(address, _abi, runner) as unknown as ErrorsLib;
  }
}
