/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IConfidentialLendingPoolView,
  IConfidentialLendingPoolViewInterface,
} from "../../../contracts/interfaces/IConfidentialLendingPoolView";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "getReserveData",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "underlyingAsset",
            type: "address",
          },
          {
            internalType: "euint64",
            name: "totalSupplied",
            type: "bytes32",
          },
          {
            internalType: "euint64",
            name: "totalBorrowed",
            type: "bytes32",
          },
          {
            internalType: "euint64",
            name: "availableLiquidity",
            type: "bytes32",
          },
          {
            internalType: "uint64",
            name: "lastUpdateTimestamp",
            type: "uint64",
          },
          {
            internalType: "bool",
            name: "active",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "borrowingEnabled",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "isCollateral",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "isPaused",
            type: "bool",
          },
          {
            internalType: "uint64",
            name: "collateralFactor",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "supplyCap",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "borrowCap",
            type: "uint64",
          },
          {
            internalType: "uint8",
            name: "decimals",
            type: "uint8",
          },
        ],
        internalType: "struct Types.ConfidentialReserve",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getReserveList",
    outputs: [
      {
        internalType: "address[]",
        name: "",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "getUserBorrowedBalance",
    outputs: [
      {
        internalType: "euint64",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "getUserPosition",
    outputs: [
      {
        components: [
          {
            internalType: "bool",
            name: "initialized",
            type: "bool",
          },
          {
            internalType: "address",
            name: "currentDebtAsset",
            type: "address",
          },
        ],
        internalType: "struct Types.ConfidentialUserPosition",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "getUserSuppliedBalance",
    outputs: [
      {
        internalType: "euint64",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IConfidentialLendingPoolView__factory {
  static readonly abi = _abi;
  static createInterface(): IConfidentialLendingPoolViewInterface {
    return new Interface(_abi) as IConfidentialLendingPoolViewInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IConfidentialLendingPoolView {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IConfidentialLendingPoolView;
  }
}
