/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace Types {
  export type ConfidentialReserveStruct = {
    underlyingAsset: AddressLike;
    totalSupplied: BytesLike;
    totalBorrowed: BytesLike;
    availableLiquidity: BytesLike;
    lastUpdateTimestamp: BigNumberish;
    active: boolean;
    borrowingEnabled: boolean;
    isCollateral: boolean;
    isPaused: boolean;
    collateralFactor: BigNumberish;
    supplyCap: BigNumberish;
    borrowCap: BigNumberish;
    decimals: BigNumberish;
  };

  export type ConfidentialReserveStructOutput = [
    underlyingAsset: string,
    totalSupplied: string,
    totalBorrowed: string,
    availableLiquidity: string,
    lastUpdateTimestamp: bigint,
    active: boolean,
    borrowingEnabled: boolean,
    isCollateral: boolean,
    isPaused: boolean,
    collateralFactor: bigint,
    supplyCap: bigint,
    borrowCap: bigint,
    decimals: bigint
  ] & {
    underlyingAsset: string;
    totalSupplied: string;
    totalBorrowed: string;
    availableLiquidity: string;
    lastUpdateTimestamp: bigint;
    active: boolean;
    borrowingEnabled: boolean;
    isCollateral: boolean;
    isPaused: boolean;
    collateralFactor: bigint;
    supplyCap: bigint;
    borrowCap: bigint;
    decimals: bigint;
  };

  export type ConfidentialUserPositionStruct = {
    initialized: boolean;
    currentDebtAsset: AddressLike;
  };

  export type ConfidentialUserPositionStructOutput = [
    initialized: boolean,
    currentDebtAsset: string
  ] & { initialized: boolean; currentDebtAsset: string };
}

export interface ConfidentialLendingPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "aclManager"
      | "borrow"
      | "cethAddress"
      | "configurator"
      | "getReserveData"
      | "getReserveList"
      | "getUserBorrowedBalance"
      | "getUserPosition"
      | "getUserSuppliedBalance"
      | "initReserve"
      | "pause"
      | "paused"
      | "priceOracle"
      | "protocolId"
      | "repay"
      | "reserveList"
      | "reserves"
      | "setCollateralAsset"
      | "setConfigurator"
      | "setPriceOracle"
      | "setUserUseReserveAsCollateral"
      | "supply"
      | "unpause"
      | "updateReserveConfig"
      | "userCollateralEnabled"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Borrow"
      | "ProtocolPaused"
      | "ProtocolUnpaused"
      | "Repay"
      | "Supply"
      | "UserCollateralChanged"
      | "Withdraw"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "aclManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "borrow",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cethAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "configurator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getReserveData",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getReserveList",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserBorrowedBalance",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserPosition",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserSuppliedBalance",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initReserve",
    values: [AddressLike, boolean, boolean, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "priceOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "repay",
    values: [AddressLike, BytesLike, BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "reserveList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "reserves",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setCollateralAsset",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setConfigurator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPriceOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setUserUseReserveAsCollateral",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "supply",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateReserveConfig",
    values: [
      AddressLike,
      boolean,
      boolean,
      boolean,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "userCollateralEnabled",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "aclManager", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "borrow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cethAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "configurator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReserveData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReserveList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserBorrowedBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserSuppliedBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "priceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "repay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reserveList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reserves", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setCollateralAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setConfigurator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPriceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUserUseReserveAsCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "supply", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateReserveConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userCollateralEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace BorrowEvent {
  export type InputTuple = [reserve: AddressLike, user: AddressLike];
  export type OutputTuple = [reserve: string, user: string];
  export interface OutputObject {
    reserve: string;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProtocolPausedEvent {
  export type InputTuple = [admin: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [admin: string, timestamp: bigint];
  export interface OutputObject {
    admin: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProtocolUnpausedEvent {
  export type InputTuple = [admin: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [admin: string, timestamp: bigint];
  export interface OutputObject {
    admin: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RepayEvent {
  export type InputTuple = [reserve: AddressLike, user: AddressLike];
  export type OutputTuple = [reserve: string, user: string];
  export interface OutputObject {
    reserve: string;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SupplyEvent {
  export type InputTuple = [reserve: AddressLike, user: AddressLike];
  export type OutputTuple = [reserve: string, user: string];
  export interface OutputObject {
    reserve: string;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserCollateralChangedEvent {
  export type InputTuple = [
    user: AddressLike,
    asset: AddressLike,
    useAsCollateral: boolean
  ];
  export type OutputTuple = [
    user: string,
    asset: string,
    useAsCollateral: boolean
  ];
  export interface OutputObject {
    user: string;
    asset: string;
    useAsCollateral: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawEvent {
  export type InputTuple = [reserve: AddressLike, user: AddressLike];
  export type OutputTuple = [reserve: string, user: string];
  export interface OutputObject {
    reserve: string;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ConfidentialLendingPool extends BaseContract {
  connect(runner?: ContractRunner | null): ConfidentialLendingPool;
  waitForDeployment(): Promise<this>;

  interface: ConfidentialLendingPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  aclManager: TypedContractMethod<[], [string], "view">;

  borrow: TypedContractMethod<
    [asset: AddressLike, amount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  cethAddress: TypedContractMethod<[], [string], "view">;

  configurator: TypedContractMethod<[], [string], "view">;

  getReserveData: TypedContractMethod<
    [asset: AddressLike],
    [Types.ConfidentialReserveStructOutput],
    "view"
  >;

  getReserveList: TypedContractMethod<[], [string[]], "view">;

  getUserBorrowedBalance: TypedContractMethod<
    [user: AddressLike, asset: AddressLike],
    [string],
    "view"
  >;

  getUserPosition: TypedContractMethod<
    [user: AddressLike],
    [Types.ConfidentialUserPositionStructOutput],
    "view"
  >;

  getUserSuppliedBalance: TypedContractMethod<
    [user: AddressLike, asset: AddressLike],
    [string],
    "view"
  >;

  initReserve: TypedContractMethod<
    [
      asset: AddressLike,
      borrowingEnabled: boolean,
      isCollateral: boolean,
      collateralFactor: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  priceOracle: TypedContractMethod<[], [string], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  repay: TypedContractMethod<
    [
      asset: AddressLike,
      amount: BytesLike,
      inputProof: BytesLike,
      isRepayingAll: boolean
    ],
    [void],
    "nonpayable"
  >;

  reserveList: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  reserves: TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        boolean,
        boolean,
        boolean,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        underlyingAsset: string;
        totalSupplied: string;
        totalBorrowed: string;
        availableLiquidity: string;
        lastUpdateTimestamp: bigint;
        active: boolean;
        borrowingEnabled: boolean;
        isCollateral: boolean;
        isPaused: boolean;
        collateralFactor: bigint;
        supplyCap: bigint;
        borrowCap: bigint;
        decimals: bigint;
      }
    ],
    "view"
  >;

  setCollateralAsset: TypedContractMethod<
    [_ceth: AddressLike],
    [void],
    "nonpayable"
  >;

  setConfigurator: TypedContractMethod<
    [_configurator: AddressLike],
    [void],
    "nonpayable"
  >;

  setPriceOracle: TypedContractMethod<
    [_priceOracle: AddressLike],
    [void],
    "nonpayable"
  >;

  setUserUseReserveAsCollateral: TypedContractMethod<
    [asset: AddressLike, useAsCollateral: boolean],
    [void],
    "nonpayable"
  >;

  supply: TypedContractMethod<
    [asset: AddressLike, amount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateReserveConfig: TypedContractMethod<
    [
      asset: AddressLike,
      active: boolean,
      borrowingEnabled: boolean,
      isCollateral: boolean,
      collateralFactor: BigNumberish,
      supplyCap: BigNumberish,
      borrowCap: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  userCollateralEnabled: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  withdraw: TypedContractMethod<
    [asset: AddressLike, amount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "aclManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "borrow"
  ): TypedContractMethod<
    [asset: AddressLike, amount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cethAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "configurator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getReserveData"
  ): TypedContractMethod<
    [asset: AddressLike],
    [Types.ConfidentialReserveStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReserveList"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getUserBorrowedBalance"
  ): TypedContractMethod<
    [user: AddressLike, asset: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserPosition"
  ): TypedContractMethod<
    [user: AddressLike],
    [Types.ConfidentialUserPositionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserSuppliedBalance"
  ): TypedContractMethod<
    [user: AddressLike, asset: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "initReserve"
  ): TypedContractMethod<
    [
      asset: AddressLike,
      borrowingEnabled: boolean,
      isCollateral: boolean,
      collateralFactor: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "priceOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "repay"
  ): TypedContractMethod<
    [
      asset: AddressLike,
      amount: BytesLike,
      inputProof: BytesLike,
      isRepayingAll: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reserveList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "reserves"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        boolean,
        boolean,
        boolean,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        underlyingAsset: string;
        totalSupplied: string;
        totalBorrowed: string;
        availableLiquidity: string;
        lastUpdateTimestamp: bigint;
        active: boolean;
        borrowingEnabled: boolean;
        isCollateral: boolean;
        isPaused: boolean;
        collateralFactor: bigint;
        supplyCap: bigint;
        borrowCap: bigint;
        decimals: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setCollateralAsset"
  ): TypedContractMethod<[_ceth: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setConfigurator"
  ): TypedContractMethod<[_configurator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPriceOracle"
  ): TypedContractMethod<[_priceOracle: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setUserUseReserveAsCollateral"
  ): TypedContractMethod<
    [asset: AddressLike, useAsCollateral: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supply"
  ): TypedContractMethod<
    [asset: AddressLike, amount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateReserveConfig"
  ): TypedContractMethod<
    [
      asset: AddressLike,
      active: boolean,
      borrowingEnabled: boolean,
      isCollateral: boolean,
      collateralFactor: BigNumberish,
      supplyCap: BigNumberish,
      borrowCap: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userCollateralEnabled"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [asset: AddressLike, amount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Borrow"
  ): TypedContractEvent<
    BorrowEvent.InputTuple,
    BorrowEvent.OutputTuple,
    BorrowEvent.OutputObject
  >;
  getEvent(
    key: "ProtocolPaused"
  ): TypedContractEvent<
    ProtocolPausedEvent.InputTuple,
    ProtocolPausedEvent.OutputTuple,
    ProtocolPausedEvent.OutputObject
  >;
  getEvent(
    key: "ProtocolUnpaused"
  ): TypedContractEvent<
    ProtocolUnpausedEvent.InputTuple,
    ProtocolUnpausedEvent.OutputTuple,
    ProtocolUnpausedEvent.OutputObject
  >;
  getEvent(
    key: "Repay"
  ): TypedContractEvent<
    RepayEvent.InputTuple,
    RepayEvent.OutputTuple,
    RepayEvent.OutputObject
  >;
  getEvent(
    key: "Supply"
  ): TypedContractEvent<
    SupplyEvent.InputTuple,
    SupplyEvent.OutputTuple,
    SupplyEvent.OutputObject
  >;
  getEvent(
    key: "UserCollateralChanged"
  ): TypedContractEvent<
    UserCollateralChangedEvent.InputTuple,
    UserCollateralChangedEvent.OutputTuple,
    UserCollateralChangedEvent.OutputObject
  >;
  getEvent(
    key: "Withdraw"
  ): TypedContractEvent<
    WithdrawEvent.InputTuple,
    WithdrawEvent.OutputTuple,
    WithdrawEvent.OutputObject
  >;

  filters: {
    "Borrow(address,address)": TypedContractEvent<
      BorrowEvent.InputTuple,
      BorrowEvent.OutputTuple,
      BorrowEvent.OutputObject
    >;
    Borrow: TypedContractEvent<
      BorrowEvent.InputTuple,
      BorrowEvent.OutputTuple,
      BorrowEvent.OutputObject
    >;

    "ProtocolPaused(address,uint64)": TypedContractEvent<
      ProtocolPausedEvent.InputTuple,
      ProtocolPausedEvent.OutputTuple,
      ProtocolPausedEvent.OutputObject
    >;
    ProtocolPaused: TypedContractEvent<
      ProtocolPausedEvent.InputTuple,
      ProtocolPausedEvent.OutputTuple,
      ProtocolPausedEvent.OutputObject
    >;

    "ProtocolUnpaused(address,uint64)": TypedContractEvent<
      ProtocolUnpausedEvent.InputTuple,
      ProtocolUnpausedEvent.OutputTuple,
      ProtocolUnpausedEvent.OutputObject
    >;
    ProtocolUnpaused: TypedContractEvent<
      ProtocolUnpausedEvent.InputTuple,
      ProtocolUnpausedEvent.OutputTuple,
      ProtocolUnpausedEvent.OutputObject
    >;

    "Repay(address,address)": TypedContractEvent<
      RepayEvent.InputTuple,
      RepayEvent.OutputTuple,
      RepayEvent.OutputObject
    >;
    Repay: TypedContractEvent<
      RepayEvent.InputTuple,
      RepayEvent.OutputTuple,
      RepayEvent.OutputObject
    >;

    "Supply(address,address)": TypedContractEvent<
      SupplyEvent.InputTuple,
      SupplyEvent.OutputTuple,
      SupplyEvent.OutputObject
    >;
    Supply: TypedContractEvent<
      SupplyEvent.InputTuple,
      SupplyEvent.OutputTuple,
      SupplyEvent.OutputObject
    >;

    "UserCollateralChanged(address,address,bool)": TypedContractEvent<
      UserCollateralChangedEvent.InputTuple,
      UserCollateralChangedEvent.OutputTuple,
      UserCollateralChangedEvent.OutputObject
    >;
    UserCollateralChanged: TypedContractEvent<
      UserCollateralChangedEvent.InputTuple,
      UserCollateralChangedEvent.OutputTuple,
      UserCollateralChangedEvent.OutputObject
    >;

    "Withdraw(address,address)": TypedContractEvent<
      WithdrawEvent.InputTuple,
      WithdrawEvent.OutputTuple,
      WithdrawEvent.OutputObject
    >;
    Withdraw: TypedContractEvent<
      WithdrawEvent.InputTuple,
      WithdrawEvent.OutputTuple,
      WithdrawEvent.OutputObject
    >;
  };
}
