/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  FunctionFragment,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
} from "../../../common";

export interface BorrowLogicInterface extends Interface {
  getEvent(
    nameOrSignatureOrTopic: "BorrowExecuted" | "RepayExecuted"
  ): EventFragment;
}

export namespace BorrowExecutedEvent {
  export type InputTuple = [
    user: AddressLike,
    asset: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [user: string, asset: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    asset: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RepayExecutedEvent {
  export type InputTuple = [
    user: AddressLike,
    asset: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [user: string, asset: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    asset: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BorrowLogic extends BaseContract {
  connect(runner?: ContractRunner | null): BorrowLogic;
  waitForDeployment(): Promise<this>;

  interface: BorrowLogicInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getEvent(
    key: "BorrowExecuted"
  ): TypedContractEvent<
    BorrowExecutedEvent.InputTuple,
    BorrowExecutedEvent.OutputTuple,
    BorrowExecutedEvent.OutputObject
  >;
  getEvent(
    key: "RepayExecuted"
  ): TypedContractEvent<
    RepayExecutedEvent.InputTuple,
    RepayExecutedEvent.OutputTuple,
    RepayExecutedEvent.OutputObject
  >;

  filters: {
    "BorrowExecuted(address,address,uint64)": TypedContractEvent<
      BorrowExecutedEvent.InputTuple,
      BorrowExecutedEvent.OutputTuple,
      BorrowExecutedEvent.OutputObject
    >;
    BorrowExecuted: TypedContractEvent<
      BorrowExecutedEvent.InputTuple,
      BorrowExecutedEvent.OutputTuple,
      BorrowExecutedEvent.OutputObject
    >;

    "RepayExecuted(address,address,uint64)": TypedContractEvent<
      RepayExecutedEvent.InputTuple,
      RepayExecutedEvent.OutputTuple,
      RepayExecutedEvent.OutputObject
    >;
    RepayExecuted: TypedContractEvent<
      RepayExecutedEvent.InputTuple,
      RepayExecutedEvent.OutputTuple,
      RepayExecutedEvent.OutputObject
    >;
  };
}
